package platzerworld.service;


import platzerworld.entities.BiergartenBE;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.Transactional;
import java.util.List;

@Stateless
public class BiergartenService {
    @PersistenceContext(unitName = "iWorld")
    private EntityManager entityManager;

    public List<BiergartenBE> getAllBiergarten() {
        entityManager.flush();
        return entityManager.createNamedQuery(BiergartenBE.FIND_ALL, BiergartenBE.class).getResultList();
    }

    @Transactional
    public void addBiergarten() {
        BiergartenBE biergartenBE = new BiergartenBE();

        biergartenBE.setName("Zum Aumeister");
        biergartenBE.setStrasse("Sondermeierstrasse 1");//
        biergartenBE.setPlz("80939");//
        biergartenBE.setOrt("München (Schwabing)");//
        biergartenBE.setTelefon("089 / 18 93 142 0");//
        biergartenBE.setEmail("aumeister@aumeister.de");
        biergartenBE.setUrl("www.aumeister.de");//
        biergartenBE.setLatitude("48,185977");
        biergartenBE.setLongitude("11,620038");
        biergartenBE.setMass("Mass");
        biergartenBE.setApfelschorle("AS");
        biergartenBE.setRiesenbreze("RB");
        biergartenBE.setObazda("Obazda");
        biergartenBE.setBiermarke("BM");
        biergartenBE.setLieblingsgericht("LG");
        biergartenBE.setSpeisekommentar("Speisekommentar");
        biergartenBE.setDescShort("DESC LONG");
        biergartenBE.setDescLong("Am Nordrand des Englischen Gartens gelegen");
        biergartenBE.setFavorit(false);//
        entityManager.persist(biergartenBE);

        biergartenBE.setName("Zum Aumeister");
        biergartenBE.setStrasse("Sondermeierstrasse 1");
        biergartenBE.setPlz("80939");
        biergartenBE.setOrt("München (Schwabing)");
        biergartenBE.setTelefon("089 / 18 93 142 0");
        biergartenBE.setEmail("aumeister@aumeister.de");
        biergartenBE.setUrl("www.aumeister.de");
        biergartenBE.setLatitude("48,185977");
        biergartenBE.setLongitude("11,620038");
        biergartenBE.setDescLong("Am Nordrand des Englischen Gartens gelegen");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Hirschgarten");
        biergartenBE.setStrasse("Hirschgarten 1");
        biergartenBE.setPlz("80639");
        biergartenBE.setOrt("München (Neuhausen)");
        biergartenBE.setTelefon("089/17 99 91 19");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.hirschgarten.de");
        biergartenBE.setLatitude("48,149882");
        biergartenBE.setLongitude("11,511167");
        biergartenBE.setDescLong("Guter Biergarten, ein echter Klassiker");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Augustinerkeller");
        biergartenBE.setStrasse("Arnulfstr. 52");
        biergartenBE.setPlz("80335");
        biergartenBE.setOrt("München");
        biergartenBE.setTelefon("089 594393");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.augustinerkeller.de");
        biergartenBE.setLatitude("48,149925");
        biergartenBE.setLongitude("11,511156");
        biergartenBE.setDescLong("Ideal, um vor der Hektik in der Innenstadt abzutauchen");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Chinesischer Turm");
        biergartenBE.setStrasse("Englischer Garten 3");
        biergartenBE.setPlz("80538");
        biergartenBE.setOrt("München");
        biergartenBE.setTelefon("089-38387320");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.chinaturm.de");
        biergartenBE.setLatitude("48,152447");
        biergartenBE.setLongitude("11,591912");
        biergartenBE.setDescLong("Bunter Biergarten im Herzen des Englischen Gartens");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Erdinger Weiübiergarten");
        biergartenBE.setStrasse("Heiglhofstr. 12");
        biergartenBE.setPlz("81377");
        biergartenBE.setOrt("München (Groühadern)");
        biergartenBE.setTelefon("089-7194300");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.gasthaus-zum-erdinger-weissbraeu.de");
        biergartenBE.setLatitude("48,112957");
        biergartenBE.setLongitude("11,478772");
        biergartenBE.setDescLong("Wunderbar schattig unter einem Dach aus Kastanien");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Franziskanergarten");
        biergartenBE.setStrasse("Friedenspromenade 45");
        biergartenBE.setPlz("81827");
        biergartenBE.setOrt("München");
        biergartenBE.setTelefon("089-4300996");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.franziskanergarten.de");
        biergartenBE.setLatitude("48,109452");
        biergartenBE.setLongitude("11,670973");
        biergartenBE.setDescLong("Klassiker unter den Biergürten mit Hausmannskost");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Freihamer Wirtshaus");
        biergartenBE.setStrasse("Freihamer Allee 21");
        biergartenBE.setPlz("81249");
        biergartenBE.setOrt("München (Freiham)");
        biergartenBE.setTelefon("089-89746991");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.freihamer-wirtshaus.de");
        biergartenBE.setLatitude("48,137055");
        biergartenBE.setLongitude("11,402382");
        biergartenBE.setDescLong("Ideal für einen Ausflug mit dem Radl");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Harlachinger Einkehr");
        biergartenBE.setStrasse("Karolinger-Allee 34");
        biergartenBE.setPlz("81545");
        biergartenBE.setOrt("München (Harlaching)");
        biergartenBE.setTelefon("089-64209093");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.harlachinger-einkehr.de");
        biergartenBE.setLatitude("48,095693");
        biergartenBE.setLongitude("11,557966");
        biergartenBE.setDescLong("Zur Happy-Hour von 16 bis 18 Uhr und ab 22 Uhr Mass Bier 5 €");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Hinterbrühl");
        biergartenBE.setStrasse("Hinterbrühl 2");
        biergartenBE.setPlz("81479");
        biergartenBE.setOrt("München (Thalkirchen)");
        biergartenBE.setTelefon("089-794494");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.www.gasthof-hinterbrühl.de");
        biergartenBE.setLatitude("48,086409");
        biergartenBE.setLongitude("11,54069");
        biergartenBE.setDescLong("Reich von Ex-Lüwenkünig Wildmooser, urig und schön");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Hirschau");
        biergartenBE.setStrasse("Gyülingerstr. 15");
        biergartenBE.setPlz("80805");
        biergartenBE.setOrt("München (Schwabing)");
        biergartenBE.setTelefon("089-3221080");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.hirschau-muenchen.de");
        biergartenBE.setLatitude("48,162031");
        biergartenBE.setLongitude("011,602587");
        biergartenBE.setDescLong("Treffpunkt der Müncher Familien mit Kindern");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Hofbrüukeller");
        biergartenBE.setStrasse("Innere Wiener Str. 19");
        biergartenBE.setPlz("81667");
        biergartenBE.setOrt("München (Haidhausen)");
        biergartenBE.setTelefon("089-4599250");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.hofbraeukeller.de");
        biergartenBE.setLatitude("48,134121");
        biergartenBE.setLongitude("11,595277");
        biergartenBE.setDescLong("Biergarten-Oase mit Sausalitos-Sommerbar");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Hopfengarten");
        biergartenBE.setStrasse("Siegenburger Str. 43");
        biergartenBE.setPlz("81373");
        biergartenBE.setOrt("München (Westpark)");
        biergartenBE.setTelefon("089-7608846");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.hopfen-garten.de");
        biergartenBE.setLatitude("48,125481");
        biergartenBE.setLongitude("11,526718");
        biergartenBE.setDescLong("Gemütlicher Biergarten mit einem groüe Spielplatz");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Iberl");
        biergartenBE.setStrasse("Wilhelm-Leibl-Str. 22");
        biergartenBE.setPlz("81479");
        biergartenBE.setOrt("München");
        biergartenBE.setTelefon("");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,070996");
        biergartenBE.setLongitude("11,5149");
        biergartenBE.setDescLong("Traumplatz an der Würm, ideal für Familienausflüge");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Laimer's");
        biergartenBE.setStrasse("Agricolastr. 16");
        biergartenBE.setPlz("80687");
        biergartenBE.setOrt("München");
        biergartenBE.setTelefon("089 5466401");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.laimers.com");
        biergartenBE.setLatitude("48,141234");
        biergartenBE.setLongitude("11,492523");
        biergartenBE.setDescLong("Gemütlicher versteckter Biergarten mit angesagter Bar");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Langwieder See");
        biergartenBE.setStrasse("Kreuzkapellenstr. 89");
        biergartenBE.setPlz("81249");
        biergartenBE.setOrt("München (Langwied)");
        biergartenBE.setTelefon("089-864860");
        biergartenBE.setEmail("");
        biergartenBE.setUrl(" www.langwiedersee.de");
        biergartenBE.setLatitude("48,197735");
        biergartenBE.setLongitude("11,414366");
        biergartenBE.setDescLong("Direkt am Seeufer gelegen, ideal nach einem Badetag");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Leiberheim");
        biergartenBE.setStrasse("Nixenweg 9");
        biergartenBE.setPlz("81739");
        biergartenBE.setOrt("München (Waldperlach)");
        biergartenBE.setTelefon("089-4300000");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.leiberheim.de");
        biergartenBE.setLatitude("48,078467");
        biergartenBE.setLongitude("11,671759");
        biergartenBE.setDescLong("Familienparadies, verschweigen, klassisch");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Löwenbräukeller");
        biergartenBE.setStrasse("Nymphenburgestr. 2");
        biergartenBE.setPlz("80335");
        biergartenBE.setOrt("München (Neuhausen)");
        biergartenBE.setTelefon("089-54726690");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.loewenbraeukeller.com");
        biergartenBE.setLatitude("48,148264");
        biergartenBE.setLongitude("11,558626");
        biergartenBE.setDescLong("Sehr sonnig");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Max-Emanuel-Brauerei");
        biergartenBE.setStrasse("Adalbertstr. 33");
        biergartenBE.setPlz("80779");
        biergartenBE.setOrt("München (Schwabing)");
        biergartenBE.setTelefon("089-2715158");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.max-emanuel-brauerei.de");
        biergartenBE.setLatitude("48,152572");
        biergartenBE.setLongitude("11,575953");
        biergartenBE.setDescLong("An der Uni, kein typischer Biergarten");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Maxhof");
        biergartenBE.setStrasse("Mühlthalerstr. 91");
        biergartenBE.setPlz("81475");
        biergartenBE.setOrt("München (Maxhof)");
        biergartenBE.setTelefon("089-75698870");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.gasthaus-maxhof.de");
        biergartenBE.setLatitude("48,086563");
        biergartenBE.setLongitude("11,478682");
        biergartenBE.setDescLong("In der Nühe des Forstenrieder Parks, mit Spielplatz");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Gutshof Menterschwaige");
        biergartenBE.setStrasse("Menterschwaigstr. 4");
        biergartenBE.setPlz("81545");
        biergartenBE.setOrt("München (Harlaching)");
        biergartenBE.setTelefon("089-640732");
        biergartenBE.setEmail("www.menterschwaige.de");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,081399");
        biergartenBE.setLongitude("11,545245");
        biergartenBE.setDescLong("Urbild eines Ausflugsbiergartens hoch über der Isar");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Michaeli-Garten");
        biergartenBE.setStrasse("Feichstr. 10");
        biergartenBE.setPlz("81735");
        biergartenBE.setOrt("München (Neuperlach)");
        biergartenBE.setTelefon("089-43552424");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.michaeligarten.de");
        biergartenBE.setLatitude("48,115355");
        biergartenBE.setLongitude("11,638518");
        biergartenBE.setDescLong("Am Ufer des Ostpark-Sees, schün zum Entspannen");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Muffatwerk");
        biergartenBE.setStrasse("Zellstraüe 4");
        biergartenBE.setPlz("81667");
        biergartenBE.setOrt("München (Haidhausen)");
        biergartenBE.setTelefon("+49-(0)89-45875073");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.muffatwerk.de/de/pages/biergarten");
        biergartenBE.setLatitude("48,132973");
        biergartenBE.setLongitude("11,588972");
        biergartenBE.setDescLong("Schattige Plütze unter Münchens grüüter Markise");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Münchner Haupt");
        biergartenBE.setStrasse("Zielstattstr. 6");
        biergartenBE.setPlz("81379");
        biergartenBE.setOrt("München (Sendling)");
        biergartenBE.setTelefon("089-786940");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.muenchnerhaupt.de");
        biergartenBE.setLatitude("48,104576");
        biergartenBE.setLongitude("11,535119");
        biergartenBE.setDescLong("Traditioneller Biergarten mit groüer Essensauswahl");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Park Cafü");
        biergartenBE.setStrasse("Sophienstr. 7");
        biergartenBE.setPlz("80333");
        biergartenBE.setOrt("München (Innenstadt)");
        biergartenBE.setTelefon("089-51617980");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.parkcafe089.de");
        biergartenBE.setLatitude("48,142478");
        biergartenBE.setLongitude("11,564746");
        biergartenBE.setDescLong("Schünes Wirtshaus, schüne Terrasse, Liegestühle");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Paulaner Brüuhaus");
        biergartenBE.setStrasse("Kapuziner Platz 5");
        biergartenBE.setPlz("80337");
        biergartenBE.setOrt("München (Sendling)");
        biergartenBE.setTelefon("089-5446110");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.paulaner-brauhaus.com/muenchen/facilities");
        biergartenBE.setLatitude("48,126479");
        biergartenBE.setLongitude("11,558783");
        biergartenBE.setDescLong("Ein echter Stadtgarten, verschiedene Saisonbiere");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Paulaner am Nockerberg");
        biergartenBE.setStrasse("Hochstr. 77");
        biergartenBE.setPlz("81541");
        biergartenBE.setOrt("München (Giesing)");
        biergartenBE.setTelefon("089-4599130");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.nockherberg.com");
        biergartenBE.setLatitude("48,121668");
        biergartenBE.setLongitude("11,582175");
        biergartenBE.setDescLong("Berühmt, moderne Service-Straüe, alte Büume");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Prinzregent-Garten");
        biergartenBE.setStrasse("Benedikterstraüe 35");
        biergartenBE.setPlz("81241");
        biergartenBE.setOrt("München (Pasing)");
        biergartenBE.setTelefon("089-8202760");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.prinzregentgarten.de");
        biergartenBE.setLatitude("48,140645");
        biergartenBE.setLongitude("11,468852");
        biergartenBE.setDescLong("Nobler Eingang, dahinter lockt Gemütlichkeit");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Rosengarten");
        biergartenBE.setStrasse("Westendstr. 305");
        biergartenBE.setPlz("81377");
        biergartenBE.setOrt("München");
        biergartenBE.setTelefon("");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,123122");
        biergartenBE.setLongitude("11,508018");
        biergartenBE.setDescLong("Schattig, groüer Abenteuerspielplatz in der Nühe");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Seehaus");
        biergartenBE.setStrasse("Kleinhesselohe 2");
        biergartenBE.setPlz("80802");
        biergartenBE.setOrt("München (Schwabing)");
        biergartenBE.setTelefon("089-3816130");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.kuffler-gastronomie.de/de/muenchen/seehaus/index.php");
        biergartenBE.setLatitude("48,160504");
        biergartenBE.setLongitude("11,598365");
        biergartenBE.setDescLong("Nicht nur für Promis, Traumlage am See");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Spektakel");
        biergartenBE.setStrasse("Pfeuferstr. 32");
        biergartenBE.setPlz("81737");
        biergartenBE.setOrt("München (Sendling)");
        biergartenBE.setTelefon("089-76758359");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.spektakel-muenchen.de");
        biergartenBE.setLatitude("48,123315");
        biergartenBE.setLongitude("11,541197");
        biergartenBE.setDescLong("Gemütlicher Nachbarschafts-Biergarten");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("St. Emmeramsmühle");
        biergartenBE.setStrasse("St. Emmeram 41");
        biergartenBE.setPlz("81925");
        biergartenBE.setOrt("München");
        biergartenBE.setTelefon("089 953971");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.emmeramsmuehle.de");
        biergartenBE.setLatitude("48,176019");
        biergartenBE.setLongitude("11,627263");
        biergartenBE.setDescLong("Klassischer Biergarten mit schünen, alten Gemüuers");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Taxisgarten");
        biergartenBE.setStrasse("Taxisstr. 12");
        biergartenBE.setPlz("80637");
        biergartenBE.setOrt("München (Neuhausen)");
        biergartenBE.setTelefon("089-156827");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.taxisgarten.de");
        biergartenBE.setLatitude("48,162679");
        biergartenBE.setLongitude("11,532211");
        biergartenBE.setDescLong("Traumhaft, um einen Abend zu genieüen, sehr beliebt");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Viktualienmarkt");
        biergartenBE.setStrasse("Viktualienmarkt 6");
        biergartenBE.setPlz("80331");
        biergartenBE.setOrt("München (Innenstadt)");
        biergartenBE.setTelefon("089-297545");
        biergartenBE.setEmail("");
        biergartenBE.setUrl(" www.biergarten-viktualienmarkt.de");
        biergartenBE.setLatitude("48,135238");
        biergartenBE.setLongitude("11,57639");
        biergartenBE.setDescLong("Mehr Flair geht nicht");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Villa Flora");
        biergartenBE.setStrasse("Hansastr. 44");
        biergartenBE.setPlz("80636");
        biergartenBE.setOrt("München");
        biergartenBE.setTelefon("");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,131672");
        biergartenBE.setLongitude("11,529931");
        biergartenBE.setDescLong("Mediterranes Flair mitten in München, keine Selbstbedienug");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Waldheim");
        biergartenBE.setStrasse("Waldheim 1");
        biergartenBE.setPlz("81377");
        biergartenBE.setOrt("München");
        biergartenBE.setTelefon("");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,102735");
        biergartenBE.setLongitude("11,478862");
        biergartenBE.setDescLong("Tüglich wechselndes Tagsgericht, Bierpass");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Weyprechthof");
        biergartenBE.setStrasse("Max-Liebermann-Str. 6");
        biergartenBE.setPlz("80937");
        biergartenBE.setOrt("München (Am Hart-Harthof)");
        biergartenBE.setTelefon("089-3111950");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.weyprechthof.de");
        biergartenBE.setLatitude("48,205563");
        biergartenBE.setLongitude("11,572136");
        biergartenBE.setDescLong("U-Bahn-Anschluss (Harthof), Dorfcharakter");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Cirkuswiese");
        biergartenBE.setStrasse("Theresienhühe 7");
        biergartenBE.setPlz("80339");
        biergartenBE.setOrt("München");
        biergartenBE.setTelefon("089-500593800");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.hacker-pschorrbraeu.de");
        biergartenBE.setLatitude("48,136394");
        biergartenBE.setLongitude("11,548508");
        biergartenBE.setDescLong("Der Biergarten Cirkuswiese befindet sich gleich neben der Theresienwiese und ist einer der am wenigsten besuchten Biergürten Münchens.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Wirtshaus Zamdorfer");
        biergartenBE.setStrasse("Schwarzwaldstr. 2a");
        biergartenBE.setPlz("81677");
        biergartenBE.setOrt("München (Bogenhausen)");
        biergartenBE.setTelefon("089-916921");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.zamdorfer.de");
        biergartenBE.setLatitude("48,139913");
        biergartenBE.setLongitude("11,628815");
        biergartenBE.setDescLong("Lauschiger Biergarten am Rand von Bogenhausen");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Zum Grünen Baum");
        biergartenBE.setStrasse("Verdistr. 47");
        biergartenBE.setPlz("81247");
        biergartenBE.setOrt("München (Obermenzing)");
        biergartenBE.setTelefon("089-81089314");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,163986");
        biergartenBE.setLongitude("11,475914");
        biergartenBE.setDescLong("Schmuckes Wirtshaus, preisgünstiges Essen");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Zum Flaucher");
        biergartenBE.setStrasse("Isarauenstr. 8");
        biergartenBE.setPlz("81379");
        biergartenBE.setOrt("München (Thalkirchen)");
        biergartenBE.setTelefon("089-7232677");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.zum-flaucher.de");
        biergartenBE.setLatitude("48,108487");
        biergartenBE.setLongitude("11,557472");
        biergartenBE.setDescLong("Super Radl-Treff, sehr schüner Kinderspielplatz");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Zum Hirschen");
        biergartenBE.setStrasse("Sollner Str. 43");
        biergartenBE.setPlz("81479");
        biergartenBE.setOrt("München");
        biergartenBE.setTelefon("");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,08105");
        biergartenBE.setLongitude("11,526835");
        biergartenBE.setDescLong("Familienfreundlicher Garten mit S-Bahn-Anschluss");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Zur Mühle");
        biergartenBE.setStrasse("Kirchplatz 5");
        biergartenBE.setPlz("85737");
        biergartenBE.setOrt("München");
        biergartenBE.setTelefon("089-960930");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.hotel-muehle.de");
        biergartenBE.setLatitude("48,226636");
        biergartenBE.setLongitude("11,674572");
        biergartenBE.setDescLong("Typischer Wirtsgarten mitten im Ort");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Alter Wirt");
        biergartenBE.setStrasse("Margaretenstr. 31");
        biergartenBE.setPlz("82152");
        biergartenBE.setOrt("Krailling");
        biergartenBE.setTelefon("089-89198444");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.alterwirtkrailling.de");
        biergartenBE.setLatitude("48,098601");
        biergartenBE.setLongitude("11,417625");
        biergartenBE.setDescLong("Schüner Traditionsbierbarten direkt an der Würm");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Alter Wirt Etterschlag");
        biergartenBE.setStrasse("Inninger Str. 6");
        biergartenBE.setPlz("82237");
        biergartenBE.setOrt("Etterschlag");
        biergartenBE.setTelefon("08153-8282");
        biergartenBE.setEmail("alterwirt@t-online.de");
        biergartenBE.setUrl("www.alter-wirt-etterschlag.de");
        biergartenBE.setLatitude("48,086114");
        biergartenBE.setLongitude("11,200545");
        biergartenBE.setDescLong("Dorfbiergarten mit festen Holzbünken, Spielplatz");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Zur Aubinger Einkehr");
        biergartenBE.setStrasse("Grüüweinsteinplatz 7");
        biergartenBE.setPlz("81249");
        biergartenBE.setOrt("München (Neuaubing)");
        biergartenBE.setTelefon("089-875581");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.zur-aubinger-einkehr.de");
        biergartenBE.setLatitude("48,143608");
        biergartenBE.setLongitude("11,416981");
        biergartenBE.setDescLong("Traditioneller Biergarten, an Feiertagen gibt es Live-Musik");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Aujüger");
        biergartenBE.setStrasse("Austraüe 4");
        biergartenBE.setPlz("82544");
        biergartenBE.setOrt("Puppling");
        biergartenBE.setTelefon("08171-78556");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.aujaeger-puppling.de");
        biergartenBE.setLatitude("47,919466");
        biergartenBE.setLongitude("11,449878");
        biergartenBE.setDescLong("Freundlich Raststation bei Wanderung oder Radtour");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Bartewirt");
        biergartenBE.setStrasse("Grubstr. 1");
        biergartenBE.setPlz("83626");
        biergartenBE.setOrt("83626 Valley/Kreuzstraüe");
        biergartenBE.setTelefon("08024-7718");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.bartewirt.de");
        biergartenBE.setLatitude("47,92075");
        biergartenBE.setLongitude("11,755291");
        biergartenBE.setDescLong("Schmucker Biergarten mit guter S-Bahn-Anbindung");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Bergl");
        biergartenBE.setStrasse("Bergl 1");
        biergartenBE.setPlz("85764");
        biergartenBE.setOrt("Oberschleiüheim");
        biergartenBE.setTelefon("089-3150105");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("http://www.hacker-pschorr.de/freizeit/gastroguide/details.php?gastroID=542");
        biergartenBE.setLatitude("48,260454");
        biergartenBE.setLongitude("11,56782");
        biergartenBE.setDescLong("Idyllischer Platz mitten im Wald, rustikales Flair");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Brauhaus Bruck");
        biergartenBE.setStrasse("Augsburger Str. 41");
        biergartenBE.setPlz("82256");
        biergartenBE.setOrt("Fürstenfeldbruck");
        biergartenBE.setTelefon("+49-(0)8141-25490");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.brauhaus-bruck.de");
        biergartenBE.setLatitude("48,182759");
        biergartenBE.setLongitude("11,252339");
        biergartenBE.setDescLong("Brauerei-Biergarten, groüer Spielplatz");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Brüustüberl Weihenstephan");
        biergartenBE.setStrasse("Weihenstephaner Berg 10");
        biergartenBE.setPlz("85354");
        biergartenBE.setOrt("Freising (Weihenstephan)");
        biergartenBE.setTelefon("08161-13004");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.braeustueberl-weihenstephan.de");
        biergartenBE.setLatitude("48,395787");
        biergartenBE.setLongitude("11,728761");
        biergartenBE.setDescLong("Angeblich ülteste Brauerei der Welt, seit 1040 in Betrieb.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Zum Bruckenfischer");
        biergartenBE.setStrasse("Dürnstein 1");
        biergartenBE.setPlz("82544");
        biergartenBE.setOrt("Egling");
        biergartenBE.setTelefon("08178-3635");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("47,971996");
        biergartenBE.setLongitude("11,476609");
        biergartenBE.setDescLong("Treff für Radler und Wanderer direkt an der Isar.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Dampfschiff");
        biergartenBE.setStrasse("Graf-Rasso-Straüe 40");
        biergartenBE.setPlz("82284");
        biergartenBE.setOrt("Grafrath");
        biergartenBE.setTelefon("+49-(0)8144-1314");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.dampfschiff.com");
        biergartenBE.setLatitude("48,123302");
        biergartenBE.setLongitude("11,156391");
        biergartenBE.setDescLong("Idylische Lage direkt an der Amper.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Diablo");
        biergartenBE.setStrasse("Rümerstr. 11");
        biergartenBE.setPlz("82205");
        biergartenBE.setOrt("Gilching");
        biergartenBE.setTelefon("");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,107539");
        biergartenBE.setLongitude("11,301885");
        biergartenBE.setDescLong("Mexikaner mit bayerischem Biergarten.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Einkehr zur Schwaige");
        biergartenBE.setStrasse("Forst-Kasten-Allee 114");
        biergartenBE.setPlz("81475");
        biergartenBE.setOrt("München (Fürstenried)");
        biergartenBE.setTelefon("+49-(0)89-7591968");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,095154");
        biergartenBE.setLongitude("11,482942");
        biergartenBE.setDescLong("Traditioneller Biergarten neben dem Schloss.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Emminger Hof");
        biergartenBE.setStrasse("Emminger Hof 1");
        biergartenBE.setPlz("86941");
        biergartenBE.setOrt("St. Ottilien");
        biergartenBE.setTelefon("08193-5238");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.emminger-hof.de");
        biergartenBE.setLatitude("48,097058");
        biergartenBE.setLongitude("11,043558");
        biergartenBE.setDescLong("Grandioser Blick auf Klostergarten und Gebirge.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Forsthaus Kasten");
        biergartenBE.setStrasse("Im Forstenrieder Park");
        biergartenBE.setPlz("82131");
        biergartenBE.setOrt("Gauting Forst Kasten");
        biergartenBE.setTelefon("089-8500360");
        biergartenBE.setEmail("");
        biergartenBE.setUrl(" www.forst-kasten.de");
        biergartenBE.setLatitude("48,075432");
        biergartenBE.setLongitude("11,416919");
        biergartenBE.setDescLong("Ruhiger Ausflugsbiergarten auf schüner Lichtung.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Fürstenfelder");
        biergartenBE.setStrasse("Fürstenfeld 15");
        biergartenBE.setPlz("82256");
        biergartenBE.setOrt("Fürstenfeldbruck");
        biergartenBE.setTelefon("08141-88875-410");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.fuerstenfelder.com");
        biergartenBE.setLatitude("48,172702");
        biergartenBE.setLongitude("11,252245");
        biergartenBE.setDescLong("Blick aufs Kloster, überweigend Bioprodukte.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Gasthof Grub");
        biergartenBE.setStrasse("Parsdorfer Str. 5");
        biergartenBE.setPlz("85586");
        biergartenBE.setOrt("Poing-Grub");
        biergartenBE.setTelefon("089-9032336");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,165051");
        biergartenBE.setLongitude("11,782354");
        biergartenBE.setDescLong("über 100 Jahre altes Wirtshaus mit viel Flair.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Gasthaus zur Mühle");
        biergartenBE.setStrasse("Mühltal 10");
        biergartenBE.setPlz("82064");
        biergartenBE.setOrt("Straülach");
        biergartenBE.setTelefon("08178-3630");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.gasthausmuehle.de");
        biergartenBE.setLatitude("47,997342");
        biergartenBE.setLongitude("11,485463");
        biergartenBE.setDescLong("Paradiesisch gelegen zwischen Wald und Isar.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Gut Keferloh");
        biergartenBE.setStrasse("Keferloh 2");
        biergartenBE.setPlz("85630");
        biergartenBE.setOrt("Grasbrunn");
        biergartenBE.setTelefon("089-469248");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.gut-keferloh.de");
        biergartenBE.setLatitude("48,095846");
        biergartenBE.setLongitude("11,727382");
        biergartenBE.setDescLong("Traditionsbiergarten, klassische Einkehr.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Heide Volm");
        biergartenBE.setStrasse("Bahnhofstr. 51");
        biergartenBE.setPlz("82152");
        biergartenBE.setOrt("Planegg");
        biergartenBE.setTelefon("089-8572029");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.heidevolm.de");
        biergartenBE.setLatitude("48,104191");
        biergartenBE.setLongitude("11,414583");
        biergartenBE.setDescLong("Neu: Brezn-Backstüberl mit Blick in die Backstube.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Heimstettener See");
        biergartenBE.setStrasse("Am Heimstettener See");
        biergartenBE.setPlz("85609");
        biergartenBE.setOrt("Aschheim");
        biergartenBE.setTelefon("089-9031697");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.heimstettenersee.de");
        biergartenBE.setLatitude("48,158131");
        biergartenBE.setLongitude("11,737542");
        biergartenBE.setDescLong("Direkt an einem kleinen Badesee.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Insel-Mühle");
        biergartenBE.setStrasse("Von-Kahr-Str. 87");
        biergartenBE.setPlz("80999");
        biergartenBE.setOrt("München (Untermenzing)");
        biergartenBE.setTelefon("089-81010");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.inselmuehle-muenchen.com");
        biergartenBE.setLatitude("48,176633");
        biergartenBE.setLongitude("11,462053");
        biergartenBE.setDescLong("Traumplatz an der Würm, ideal für Familienausflüge.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Kloster Andechs Brüustüberl");
        biergartenBE.setStrasse("Bergstraüe 2");
        biergartenBE.setPlz("82346");
        biergartenBE.setOrt("Erling-Andechs");
        biergartenBE.setTelefon("+49-(0)8152-3760");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.andechs.de");
        biergartenBE.setLatitude("47,973729");
        biergartenBE.setLongitude("11,183481");
        biergartenBE.setDescLong("Berühmt für sein Bier, der Aufstieg lohnt sich.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Klosterbrüu Schüftlarn");
        biergartenBE.setStrasse("Kloster Schüftlarn 16");
        biergartenBE.setPlz("82067");
        biergartenBE.setOrt("Ebenhausen-Schüftlarn");
        biergartenBE.setTelefon("08178-3694");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.klosterbraeustueberl-schaeftlarn.de");
        biergartenBE.setLatitude("47,978105");
        biergartenBE.setLongitude("11,466288");
        biergartenBE.setDescLong("Im  Isartalgrund gelegen, sehr schüner Ausblick.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Kottmeier");
        biergartenBE.setStrasse("Brüuhausstr. 18");
        biergartenBE.setPlz("82152");
        biergartenBE.setOrt("Planegg");
        biergartenBE.setTelefon("");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,105576");
        biergartenBE.setLongitude("11,422949");
        biergartenBE.setDescLong("Direkt am Ufer der Würm, groüe Essensauswahl.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Kugler-Alm");
        biergartenBE.setStrasse("Linienstr. 93");
        biergartenBE.setPlz("82041");
        biergartenBE.setOrt("Deisenhofen");
        biergartenBE.setTelefon("089-61390120");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.kugleralm.de");
        biergartenBE.setLatitude("48,035897");
        biergartenBE.setLongitude("11,575076");
        biergartenBE.setDescLong("Schüner Familenbiergarten, perfekt für Radl-Touren.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Landgasthof Alter Wirt");
        biergartenBE.setStrasse("Hauptstr. 36");
        biergartenBE.setPlz("85716");
        biergartenBE.setOrt("Unterschleiüheim");
        biergartenBE.setTelefon("089-3707340");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.alterwirt-ush.de");
        biergartenBE.setLatitude("48,277442");
        biergartenBE.setLongitude("11,567654");
        biergartenBE.setDescLong("Staatliches denkmalgeschütztes Wirtshaus.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Schlossgaststütte Leutstetten");
        biergartenBE.setStrasse("Altostraüe 11");
        biergartenBE.setPlz("82319");
        biergartenBE.setOrt("Starnberg (Leutstetten)");
        biergartenBE.setTelefon("08151-8156");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.schlossgaststaette-leutstetten.de");
        biergartenBE.setLatitude("48,029872");
        biergartenBE.setLongitude("11,368519");
        biergartenBE.setDescLong("Ideal für Wanderungen, griabig und schattig.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Lochhamer's");
        biergartenBE.setStrasse("Lochhamer Str. 4");
        biergartenBE.setPlz("82166");
        biergartenBE.setOrt("Grüfelfing");
        biergartenBE.setTelefon("089-85484651");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,125668");
        biergartenBE.setLongitude("11,442231");
        biergartenBE.setDescLong("Von Wasserrad angetriebener Hendlgrill.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Maisinger Seehof");
        biergartenBE.setStrasse("Seestr. 14");
        biergartenBE.setPlz("82343");
        biergartenBE.setOrt("Maising-Pücking");
        biergartenBE.setTelefon("08151-744242");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("47,981658");
        biergartenBE.setLongitude("11,282774");
        biergartenBE.setDescLong("Der Biergarten Maisinger Seehof befindet sich direkt am Maisinger See.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Plantage!");
        biergartenBE.setStrasse("Plantage 2");
        biergartenBE.setPlz("85354");
        biergartenBE.setOrt("Freising");
        biergartenBE.setTelefon("08161-63155");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.plantage-freising.de");
        biergartenBE.setLatitude("48,416436");
        biergartenBE.setLongitude("11,727771");
        biergartenBE.setDescLong("Kleinod im Wald, an Sonn- und Feiertagen Live-Musik.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Rüuber-Kneiül-Garten");
        biergartenBE.setStrasse("Hauptstr. 24");
        biergartenBE.setPlz("82216");
        biergartenBE.setOrt("Maisach");
        biergartenBE.setTelefon("");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,217029");
        biergartenBE.setLongitude("11,263553");
        biergartenBE.setDescLong("Bekann für Kneiül Dunkel, wird hier frisch gebraut.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Schloüwirtschaft Oberschleiüheim");
        biergartenBE.setStrasse("Maximilianshof 2");
        biergartenBE.setPlz("85764");
        biergartenBE.setOrt("Oberschleiüheim");
        biergartenBE.setTelefon("089-3151555");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.schlosswirtschaft-oberschleissheim.de");
        biergartenBE.setLatitude("48,248117");
        biergartenBE.setLongitude("11,558886");
        biergartenBE.setDescLong("Alte Kastanien, sehr schattig, Blick aufs Schloss.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Schlosswirtschaft Mariabrunn");
        biergartenBE.setStrasse("Gut Mariabrunn 3");
        biergartenBE.setPlz("85244");
        biergartenBE.setOrt("Rührmoos");
        biergartenBE.setTelefon("08139-8661");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.schlosswirtschaft-mariabrunn.de");
        biergartenBE.setLatitude("48,312658");
        biergartenBE.setLongitude("11,478068");
        biergartenBE.setDescLong("Natur, Kirche, Brauerei, Ruhe - kurz: Traumgarten.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Schweiger's Landgasthof");
        biergartenBE.setStrasse("Manhartsdorf 2-4");
        biergartenBE.setPlz("85456");
        biergartenBE.setOrt("Wartenberg");
        biergartenBE.setTelefon("");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,388791");
        biergartenBE.setLongitude("11,94609");
        biergartenBE.setDescLong("Ein idyllischer Kasteniengarten am S-Bahn-Halt Grub.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Seehaus Schreyegg");
        biergartenBE.setStrasse("Landsbergerstr. 78");
        biergartenBE.setPlz("82266");
        biergartenBE.setOrt("Inning am Ammersee");
        biergartenBE.setTelefon("");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,077009");
        biergartenBE.setLongitude("11,132905");
        biergartenBE.setDescLong("Innen sehr nobel, Tische direkt am Seeufer.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Seehof Herrsching");
        biergartenBE.setStrasse("Seestr. 58");
        biergartenBE.setPlz("82211");
        biergartenBE.setOrt("Herrsching");
        biergartenBE.setTelefon("+49-(0)8152-9350");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.seehof-ammersee.de");
        biergartenBE.setLatitude("47,995226");
        biergartenBE.setLongitude("11,169225");
        biergartenBE.setDescLong("Seepromenade führt mitten durch, Postkartenblick.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Seepost");
        biergartenBE.setStrasse("Bahnhofstraüe 2");
        biergartenBE.setPlz("86938");
        biergartenBE.setOrt("Schondorf am Ammersee");
        biergartenBE.setTelefon("08192-933753");
        biergartenBE.setEmail("");
        biergartenBE.setUrl(" www.seepost-ammersee.de");
        biergartenBE.setLatitude("48,052764");
        biergartenBE.setLongitude("11,100346");
        biergartenBE.setDescLong("Behübiger Biergarten am Ammerseeufer mit Dampfersteg.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Tutzinger Biergarten");
        biergartenBE.setStrasse("Midgardstr. 3-5");
        biergartenBE.setPlz("82327");
        biergartenBE.setOrt("Tutzing");
        biergartenBE.setTelefon("+49-(0)8158-1216");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.haering-wirtschaft.de");
        biergartenBE.setLatitude("47,913829");
        biergartenBE.setLongitude("11,288334");
        biergartenBE.setDescLong("Nur durch den Uferweg vom See getrennt.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Waldgasthof Buchenhain");
        biergartenBE.setStrasse("Am Klettergarten 7");
        biergartenBE.setPlz("82065");
        biergartenBE.setOrt("Buchhain");
        biergartenBE.setTelefon("089-7930124");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.hotelbuchenhain.de");
        biergartenBE.setLatitude("48,030548");
        biergartenBE.setLongitude("11,498265");
        biergartenBE.setDescLong("Viele Brotzeiten, alte Büume und viel Platz für Kinder.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Waldwirtschaft Groühesselohe");
        biergartenBE.setStrasse("Georg-Kalb-Str. 3");
        biergartenBE.setPlz("82049");
        biergartenBE.setOrt("Groühesselohe");
        biergartenBE.setTelefon("");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,067046");
        biergartenBE.setLongitude("11,5394");
        biergartenBE.setDescLong("Südlich von München.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Bavariapark");
        biergartenBE.setStrasse("Theresienhühe 15");
        biergartenBE.setPlz("80339");
        biergartenBE.setOrt("München");
        biergartenBE.setTelefon("");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,131635");
        biergartenBE.setLongitude("11,544043");
        biergartenBE.setDescLong("Wirtshaus am Bavariapark mit Augustiner Biergarten auf der Theresienhühe");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Concordia Park");
        biergartenBE.setStrasse("Landshuter Allee 165");
        biergartenBE.setPlz("80637");
        biergartenBE.setOrt("München (Neuhausen)");
        biergartenBE.setTelefon("089-155241");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,163593");
        biergartenBE.setLongitude("11,535422");
        biergartenBE.setDescLong("Concordia Park ist ein nicht so bekannter Biergarten im Münchner Stadtteil Neuhausen.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Neue Fasanerie");
        biergartenBE.setStrasse("Hartmannshofstraüe 20");
        biergartenBE.setPlz("80997");
        biergartenBE.setOrt("München (Moosach)");
        biergartenBE.setTelefon("089-1495607");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.neue-fasanerie.de");
        biergartenBE.setLatitude("48,173141");
        biergartenBE.setLongitude("11,493296");
        biergartenBE.setDescLong("Das Restaurant Neue Fasanerie liegt idyllisch im Hartmannshofer Park.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Gasthaus Siebenbrunn");
        biergartenBE.setStrasse("Siebenbrunner Straüe 5");
        biergartenBE.setPlz("81543");
        biergartenBE.setOrt("München (Thalkirchen)");
        biergartenBE.setTelefon("089-80033777");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.biergarten-siebenbrunn.de");
        biergartenBE.setLatitude("48,099844");
        biergartenBE.setLongitude("11,560594");
        biergartenBE.setDescLong(" Inmitten des grünen Landschaftsschutzgebietes Isarauen ü� direkt neben dem Tierpark Hellabrunn. Die lüngste Abendsonne genieüen");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Tassilogarten");
        biergartenBE.setStrasse("Auerfeldstraüe 18");
        biergartenBE.setPlz("81541");
        biergartenBE.setOrt("München");
        biergartenBE.setTelefon("");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,123296");
        biergartenBE.setLongitude("11,595444");
        biergartenBE.setDescLong("Der Tassilogarten ist ein sonniger Treffpunkt in Haidhausen für ein gemischtes Publikum.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("ü�s Truderinger Wirtshaus");
        biergartenBE.setStrasse("Kirchtruderinger Straüe 17");
        biergartenBE.setPlz("81829");
        biergartenBE.setOrt("München");
        biergartenBE.setTelefon("");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,1259");
        biergartenBE.setLongitude("11,674258");
        biergartenBE.setDescLong("ü�s Truderinger Wirtshaus steht für groüe Portionen, nette Leute und vernünftige Preise.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Osterwaldgarten");
        biergartenBE.setStrasse("Keferstraüe 12");
        biergartenBE.setPlz("80802");
        biergartenBE.setOrt("München");
        biergartenBE.setTelefon("");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,161828");
        biergartenBE.setLongitude("11,594308");
        biergartenBE.setDescLong("Der Osterwaldgarten lockt ein buntes Publikum an ü� und biete gute Saisonküche. ");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Mangostin Garden");
        biergartenBE.setStrasse("Maria-Einsiedel-Straüe 2");
        biergartenBE.setPlz("81379");
        biergartenBE.setOrt("München");
        biergartenBE.setTelefon("");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,100173");
        biergartenBE.setLongitude("11,546052");
        biergartenBE.setDescLong("Das Mangostin Garden kombiniert asiatische Küche mit bayerischer Tradition.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Alte Villa");
        biergartenBE.setStrasse("Seestraüe 32");
        biergartenBE.setPlz("86919");
        biergartenBE.setOrt("Utting am Ammersee");
        biergartenBE.setTelefon("08806-534456");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.alte-villa-biergarten.de");
        biergartenBE.setLatitude("48,026292");
        biergartenBE.setLongitude("11,098021");
        biergartenBE.setDescLong("Der Biergarten Alte Villa befindet sich neben einer alten bayrischen Villa am Ammersee, südwestlich von München.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Alter Wirt Ramersdorf");
        biergartenBE.setStrasse("Aribonenstraüe 8");
        biergartenBE.setPlz("81669");
        biergartenBE.setOrt("München (Ramersdorf)");
        biergartenBE.setTelefon("089-6891862");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.alterwirt-muenchen.de");
        biergartenBE.setLatitude("48,11502");
        biergartenBE.setLongitude("11,61527");
        biergartenBE.setDescLong("Den Alter Wirt Ramersdorf im Münchner Ortsteil Ramersdorf gibt es seit 1504");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Mühlenpark");
        biergartenBE.setStrasse("Mühlgasse 48");
        biergartenBE.setPlz("85748");
        biergartenBE.setOrt("Garching");
        biergartenBE.setTelefon("089-3204975");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.biergarten-muehlenpark.de");
        biergartenBE.setLatitude("48,246272");
        biergartenBE.setLongitude("11,661435");
        biergartenBE.setDescLong("Der Biergarten befindet sich auf dem Anwesen einer ehemaligen Holz- und Getreidemühle nühe Garching.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Bootshaus");
        biergartenBE.setStrasse("Zentrallündstraüe 16");
        biergartenBE.setPlz("81379");
        biergartenBE.setOrt("München (Thalkirchen)");
        biergartenBE.setTelefon("089-78017761");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,098905");
        biergartenBE.setLongitude("11,547634");
        biergartenBE.setDescLong("Der Bootshaus Biergarten befindet sich im Münchner Stadtteil Thalkirchen, unweit vom Tierpark und nur einen kleinen Fuümarsch von der Isar entfernt.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Brückerl");
        biergartenBE.setStrasse("Goteboldstr. 189");
        biergartenBE.setPlz("81249");
        biergartenBE.setOrt("München");
        biergartenBE.setTelefon("089-81896164");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.brueckerl-langwied.de");
        biergartenBE.setLatitude("48,191536");
        biergartenBE.setLongitude("11,421795");
        biergartenBE.setDescLong("Der sehr kleine Brückerl Biergarten befindet sich am Langwieder Bach unweit vom Langwieder See");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Fischer");
        biergartenBE.setStrasse("Landsberger Straüe 79");
        biergartenBE.setPlz("82266");
        biergartenBE.setOrt("Stegen am Ammersee");
        biergartenBE.setTelefon("08143-447655");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.fischer-stegen.com");
        biergartenBE.setLatitude("48,077281");
        biergartenBE.setLongitude("11.131932");
        biergartenBE.setDescLong("Der Fischer Biergarten befindet sich direkt am nürdlichsten Ufer vom Ammersee");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Forsthaus St. Hubertus");
        biergartenBE.setStrasse("St. Hubertus 1");
        biergartenBE.setPlz("85560");
        biergartenBE.setOrt("Ebersberg");
        biergartenBE.setTelefon("08092-8579996");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.forsthaus-hubertus.de");
        biergartenBE.setLatitude("48,107992");
        biergartenBE.setLongitude("11,932561");
        biergartenBE.setDescLong("Das Forsthaus St. Hubertus befindet sich inmitten des Ebersberger Forst's, cirka 35 Kilometer üstlich von München.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Grünwalder Forstwirt");
        biergartenBE.setStrasse("Riedweg 41");
        biergartenBE.setPlz("82067");
        biergartenBE.setOrt("Straülach");
        biergartenBE.setTelefon("08170-213");
        biergartenBE.setEmail("");
        biergartenBE.setUrl(" www.gruenwalder-forstwirt.de");
        biergartenBE.setLatitude("48,011819");
        biergartenBE.setLongitude("11,522553");
        biergartenBE.setDescLong("Der Grünwalder Forstwirt befindet sich in idyllischer Lage auf einem 30.000mü Grundstück in Straülach, 16 Kilometer vom Münchner Stadtzentrum entfernt.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Hofbrauhaus-Keller Freising");
        biergartenBE.setStrasse("Lankesbergstraüe 5");
        biergartenBE.setPlz("85356");
        biergartenBE.setOrt("Freising");
        biergartenBE.setTelefon("08161-938800");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,406286");
        biergartenBE.setLongitude("11,748317");
        biergartenBE.setDescLong("Der Hofbrauhaus-Keller befindet sich in einer ruhigen Wohngegend am Lankesberg in Freising");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Waldwirtschaft Hohenlindener Sauschütt");
        biergartenBE.setStrasse("Sauschütt 1");
        biergartenBE.setPlz("85664");
        biergartenBE.setOrt("Hohenlinden");
        biergartenBE.setTelefon("08124-446478");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,157115");
        biergartenBE.setLongitude("11,996542");
        biergartenBE.setDescLong("Der Hohenlindener Sauschütt Biergarten befindet sich im üstlichen Teil vom Ebersberger Forst, cirka 35 Kilometer üstlich von München.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Kloster Andechs Biergarten");
        biergartenBE.setStrasse("Bergstraüe 2");
        biergartenBE.setPlz("82346");
        biergartenBE.setOrt("Erling-Andechs");
        biergartenBE.setTelefon("08152-3760");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.andechs.de");
        biergartenBE.setLatitude("47,973729");
        biergartenBE.setLongitude("11,183481");
        biergartenBE.setDescLong("Der Biergarten von Kloster Andechs befindet sich innerhalb der Klostermauern von Andechs.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Kraillinger Brauerei");
        biergartenBE.setStrasse("Margaretenstraüe 59");
        biergartenBE.setPlz("82152");
        biergartenBE.setOrt("Krailling");
        biergartenBE.setTelefon("089-8571718");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.kraillinger-brauerei.de");
        biergartenBE.setLatitude("48,096369");
        biergartenBE.setLongitude("11,411099");
        biergartenBE.setDescLong("Klassischer Biergarten direkt an der Würm in Krailling");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Landgasthof Langwied");
        biergartenBE.setStrasse("Waidachanger 9");
        biergartenBE.setPlz("81249");
        biergartenBE.setOrt("München");
        biergartenBE.setTelefon("089-89546184");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.landgasthof-langwied.com");
        biergartenBE.setLatitude("48,181381");
        biergartenBE.setLongitude("11,423405");
        biergartenBE.setDescLong("Der Landgasthof Langwied Hotel, Restaurant und Biergarten befindet sich im kleinen Dorf Langwied.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Lindengarten");
        biergartenBE.setStrasse("Solalindernstr. 50");
        biergartenBE.setPlz("81825");
        biergartenBE.setOrt("München");
        biergartenBE.setTelefon("+49-(0)89-430 9178");
        biergartenBE.setEmail("info@lindengarten.eu");
        biergartenBE.setUrl("www.lindengarten.eu");
        biergartenBE.setLatitude("48,115028");
        biergartenBE.setLongitude("11,678488");
        biergartenBE.setDescLong("Truderinger Traditionswirtshaus Lindengarten mit Biergarten.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Liebhard's Brüustüberl zu Aying");
        biergartenBE.setStrasse("Münchener Straüe 2");
        biergartenBE.setPlz("85653");
        biergartenBE.setOrt("Aying");
        biergartenBE.setTelefon("08095-1345");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.liebhards-aying.de");
        biergartenBE.setLatitude("47,97101");
        biergartenBE.setLongitude("11,77983");
        biergartenBE.setDescLong("Liebhard's Brüustüberl Restaurant und Biergarten befindet sich in Aying.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Olympia-Alm");
        biergartenBE.setStrasse("Martin-Luther-King Weg 8");
        biergartenBE.setPlz("80809");
        biergartenBE.setOrt("München");
        biergartenBE.setTelefon("089-3009924");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.olympiaalm.de");
        biergartenBE.setLatitude("48,171114");
        biergartenBE.setLongitude("11,554349");
        biergartenBE.setDescLong("Olympia-Alm im Olympia-Park");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Paulaner Seegarten");
        biergartenBE.setStrasse("Hochstraüe 71");
        biergartenBE.setPlz("85757");
        biergartenBE.setOrt("Karlsfeld");
        biergartenBE.setTelefon("08131 3909420");
        biergartenBE.setEmail("info@paulaner-seegarten.de");
        biergartenBE.setUrl("www.paulaner-seegarten.de");
        biergartenBE.setLatitude("48,236872");
        biergartenBE.setLongitude("11,472543");
        biergartenBE.setDescLong("Der Seegarten liegt direkt am Karlsfelder See und bietet eine gute Müglichkeit, in schüner Umgebung zu speisen und/oder die Seele baumeln zu lassen.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Pe. Es. Kottmeier");
        biergartenBE.setStrasse("Brüuhausstraüe 18");
        biergartenBE.setPlz("82152");
        biergartenBE.setOrt("Planegg");
        biergartenBE.setTelefon("089-89930030");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.pe-es.de");
        biergartenBE.setLatitude("48,10553");
        biergartenBE.setLongitude("11,423055");
        biergartenBE.setDescLong("Das Pe. Es. Kottmeier befindet sich in Planegg, südwestlich von München's Innenstadt.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Postgarten");
        biergartenBE.setStrasse("Andechstrasse 1");
        biergartenBE.setPlz("82211");
        biergartenBE.setOrt("Herrsching");
        biergartenBE.setTelefon("08152 396 270");
        biergartenBE.setEmail("");
        biergartenBE.setUrl(" www.post-herrsching.de");
        biergartenBE.setLatitude("47,998044");
        biergartenBE.setLongitude("11,177318");
        biergartenBE.setDescLong("Der Biergarten Postgarten befindet sich in dem kleinen Stüdtchen Herrsching, am Ostufer vom Ammersee gelegen.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Schiaün");
        biergartenBE.setStrasse("Neues Schieüfeld 2");
        biergartenBE.setPlz("854345");
        biergartenBE.setOrt("Erding");
        biergartenBE.setTelefon("08122-8809890");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("schiassn.com");
        biergartenBE.setLatitude("48,313891");
        biergartenBE.setLongitude("11,910569");
        biergartenBE.setDescLong("Der 2010 erüffnete Biergarten Schiaün befindet sich in der Stadt Erding.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Schieüstütte Allach");
        biergartenBE.setStrasse("Servetstraüe 1");
        biergartenBE.setPlz("80999 ");
        biergartenBE.setOrt("München (Allach)");
        biergartenBE.setTelefon("089-189229-13");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("");
        biergartenBE.setLatitude("48,195731");
        biergartenBE.setLongitude("11,456144");
        biergartenBE.setDescLong("Der Biergarten Schieüstütte Allach liegt an der Fahrradroute Pasing - Dachau, immer der Würm entlang. ");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Schlossallee Haag");
        biergartenBE.setStrasse("Freisinger Straüe 1");
        biergartenBE.setPlz("85410");
        biergartenBE.setOrt("Haag an der Amper");
        biergartenBE.setTelefon("08167-350");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.biergarten-haag.de");
        biergartenBE.setLatitude("48,458249");
        biergartenBE.setLongitude("11,832423");
        biergartenBE.setDescLong("Der Biergarten Schlossallee Haag befindet sich nahe dem Fluü Amper, nur einige Kilometer nürdlich von Freising.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Schloss Dachau Biergarten");
        biergartenBE.setStrasse("Schloüstraüe 2");
        biergartenBE.setPlz("85221");
        biergartenBE.setOrt("Dachau");
        biergartenBE.setTelefon("08131-2799278");
        biergartenBE.setEmail("");
        biergartenBE.setUrl("www.schloss-dachau.com");
        biergartenBE.setLatitude("48,258399");
        biergartenBE.setLongitude("11,433463");
        biergartenBE.setDescLong("Der kleine Biergarten befindet sich am Renaissance Schloü in Dachau.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Seehaus Schreyegg");
        biergartenBE.setStrasse("Landsberger Straüe 78");
        biergartenBE.setPlz("82266");
        biergartenBE.setOrt("Stegen am Ammersee");
        biergartenBE.setTelefon("08143-992537");
        biergartenBE.setEmail("");
        biergartenBE.setUrl(" www.seehaus-schreyegg.com");
        biergartenBE.setLatitude("48,076991");
        biergartenBE.setLongitude("11,132922");
        biergartenBE.setDescLong("Der Seehaus Schreyegg Biergarten befindet sich in dem kleinen Dorf Stegen am nürdlichsten Ende vom Ammersee.");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);
        biergartenBE = new BiergartenBE();
        biergartenBE.setName("Wirtshaus am Hart");
        biergartenBE.setStrasse("Sudetendeutsche Straüe 40");
        biergartenBE.setPlz("80937");
        biergartenBE.setOrt("München (Am Hart)");
        biergartenBE.setTelefon("");
        biergartenBE.setEmail("089-3116039");
        biergartenBE.setUrl("www.theater-platzl.de");
        biergartenBE.setLatitude("48,196493");
        biergartenBE.setLongitude("11,576453");
        biergartenBE.setDescLong("");
        biergartenBE.setFavorit(false);
        entityManager.persist(biergartenBE);

    }
}
